service: default

runtime: python27
api_version: 1
threadsafe: true

env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: 1
    CLOUDSQL_DATABASE_NAME: mysqldb
    CLOUDSQL_CONNECTION_NAME: mgt660-strongfeather:us-east1:mysql

#beta_settings:
#    cloud_sql_instances: mgt660-strongfeather:northamerica-northeast1:mgt660-strongfeather

handlers:

- url: /public
  static_dir: public
  secure: always

- url: /public/app
  static_dir: public/app
  secure: always

- url: /public/assets
  static_dir: public/assets
  secure: always

- url: /public/components
  static_dir: public/components
  secure: always

- url: /public/components/event
  static_dir: public/components/event
  secure: always

- url: /public/components/register
  static_dir: public/components/register
  secure: always

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: MySQLdb
  version: "latest"